import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { GitHub, Linkedin, Twitter, Instagram, MapPin } from 'react-feather'
import Flag from 'react-flagkit'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.col}>
          <picture>
            <Image src="/images/avatar.jpeg" alt="Foto Vinícius" width={540} height={593} />
          </picture>
        </div>
        <div className={`${styles.contentText} ${styles.col}`}>
          <div className={styles.contentHeader}>
            <div>
              <small>
                <MapPin size={20} />
                Brasília-DF
              </small>
              <div>
                <Flag country="US" />
              </div>
              <div>
                <Flag country="BR" />
              </div>
            </div>
          </div>

          <div>
            <h1>Vinícius Paixão</h1>
            <h2>Desenvolvedor web<span> Front-end &amp; Designer</span></h2>
          </div>

          <div className={styles.contentFooter}>
            <hr />
            <ul className={styles.social}>
              <li><a href="https://github.com/vinipaixaors/" title="Github"><GitHub size={24} /></a></li>
              <li><a href="https://www.linkedin.com/in/viniciuspaixaors/" title="Linkedin"><Linkedin size={24} /></a></li>
              <li><a href="https://twitter.com/viniciuspaixaor" title="Twitter"><Twitter size={24} /></a></li>
              <li><a href="https://www.instagram.com/viniciuspaixaors/" title="Instagram"><Instagram size={24} /></a></li>
            </ul>
            {/* 
            <ul className={styles.perosnalContact}>
              <li className={styles.local}>
                <strong>Local</strong>
                <span>Brasília, DF</span>
              </li>
              <li className={styles.whatsapp}>
                <strong>Whatsapp</strong>
                <span>
                  <Link to="/#ligar">(61) 9 9999-9999</Link>
                  <Link to="/#ligar2">(61) 9 9999-8888</Link>
                </span>
              </li>
              <li className={styles.email}>
                <strong>E-mail</strong>
                <span>
                  <a href="mailto:"></a>
                </span>
              </li>
            </ul> 
          */}
          </div>


        </div>

      </header>

      <main className={styles.main}>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
